### ISSUE TITLE
Doesn't work with current pip and wheel

### ISSUE THREAD

**Issue by dmopalmer** [wimglenn/johnnydep#12]
As you mentioned in [https://stackoverflow.com/questions/11147667/is-there-a-way-to-list-pip-dependencies-requirements](url) it is incompatible with pip-10.0.1 .  Downgrading to pip==9.0.3 it seems to be incompatible with wheel=0.31.1=py36_0
```
(test) % johnnydep johnnydep
Traceback (most recent call last):
  File "/Users/palmer/anaconda/envs/test/bin/johnnydep", line 7, in <module>
    from johnnydep.cli import main
  File "/Users/palmer/anaconda/envs/test/lib/python3.6/site-packages/johnnydep/cli.py", line 9, in <module>
    from johnnydep.lib import DEFAULT_INDEX
  File "/Users/palmer/anaconda/envs/test/lib/python3.6/site-packages/johnnydep/lib.py", line 22, in <module>
    from wheel.metadata import pkginfo_to_dict
ImportError: cannot import name 'pkginfo_to_dict'
```

It succeeds with  wheel=0.30.0=py36h5eb2c71_1 . (installed with conda).

I see there is already a pull request for the wheel issue.

**Comment by wimglenn** [comment]
Hi, I'm aware of the issue, and a new release is in progress.  If you don't want to wait, you can continue to use the existing release in a venv with pinned `pip==9.0.3` and `wheel==0.30.0`.
