### ISSUE TITLE
DistributionNotFound error

### ISSUE THREAD

**Issue by noamilshtein** [wimglenn/johnnydep#139]
Hi all,
I use a docker image of python 3., install johnnydep using pip and the `johnnydep --output-format=pinned langflow==0.0.31`
 
when i run `johnnydep --output-format=pinned langflow==0.0.31` i get this error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/johnnydep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/johnnydep/cli.py", line 135, in main
    rendered = dist.serialise(
  File "/usr/local/lib/python3.9/site-packages/johnnydep/lib.py", line 307, in serialise
    data += [d for dep in deps for d in dep.serialise(fields=fields, recurse=False)]
  File "/usr/local/lib/python3.9/site-packages/johnnydep/lib.py", line 307, in <listcomp>
    data += [d for dep in deps for d in dep.serialise(fields=fields, recurse=False)]
  File "/usr/local/lib/python3.9/site-packages/johnnydep/lib.py", line 392, in flatten_deps
    raise JohnnyError(msg.format(dist.name, dist.specifier))
johnnydep.lib.JohnnyError: Could not find satisfactory version for libdeeplake==0.0.134
```

however when i run `pip install langflow==0.0.31` i have no errors.
could it be that johnnydep dependencies conflicts with  langflow==0.0.31 dependencies?

**Comment by noamilshtein** [comment]
solved with the following flow:
install johnnydep
create a new venv and install wheel 
run johnnydep with -p flag pointing to the venv's bin/python

**Comment by noamilshtein** [comment]
happens when the output format is pinned
