### ISSUE TITLE
UnicodeEncodeError when running in ubuntu Docker

### ISSUE THREAD

**Issue by jzeimen** [wimglenn/johnnydep#31]
I'm seeing this UnicodeEncodeError when I run johnnydep in Docker, not sure why this would be different. It works fine in a conda environment on macOS. Here's a minimal Dockerfile you could run to see the issue. 

```
FROM ubuntu

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-setuptools \
        python3-pip

RUN pip3 install johnnydep
RUN johnnydep johnnydep
```

Which then shows the error:
```
Step 4/4 : RUN johnnydep johnnydep
 ---> Running in ca6379038c29
2018-12-28 19:50:37 [info     ] init johnnydist                [johnnydep.lib] dist=johnnydep parent=None
2018-12-28 19:50:38 [info     ] init johnnydist                [johnnydep.lib] dist=anytree parent=johnnydep
2018-12-28 19:50:39 [info     ] init johnnydist                [johnnydep.lib] dist=cachetools parent=johnnydep
2018-12-28 19:50:41 [info     ] init johnnydist                [johnnydep.lib] dist=colorama parent=johnnydep
2018-12-28 19:50:42 [info     ] init johnnydist                [johnnydep.lib] dist=oyaml parent=johnnydep
2018-12-28 19:50:43 [info     ] init johnnydist                [johnnydep.lib] dist=packaging>=17 parent=johnnydep
2018-12-28 19:50:44 [info     ] init johnnydist                [johnnydep.lib] dist=pip parent=johnnydep
2018-12-28 19:50:45 [info     ] init johnnydist                [johnnydep.lib] dist=pkginfo>=1.4.2 parent=johnnydep
2018-12-28 19:50:46 [info     ] init johnnydist                [johnnydep.lib] dist=pytoml parent=johnnydep
2018-12-28 19:50:48 [info     ] init johnnydist                [johnnydep.lib] dist=setuptools>=38.3 parent=johnnydep
2018-12-28 19:50:49 [info     ] init johnnydist                [johnnydep.lib] dist=structlog parent=johnnydep
2018-12-28 19:50:50 [info     ] init johnnydist                [johnnydep.lib] dist=tabulate parent=johnnydep
2018-12-28 19:50:51 [info     ] init johnnydist                [johnnydep.lib] dist=wheel>=0.32.0 parent=johnnydep
2018-12-28 19:50:52 [info     ] init johnnydist                [johnnydep.lib] dist=wimpy parent=johnnydep
2018-12-28 19:50:53 [info     ] init johnnydist                [johnnydep.lib] dist=six>=1.9.0 parent=anytree
2018-12-28 19:50:54 [info     ] init johnnydist                [johnnydep.lib] dist=pyyaml parent=oyaml
2018-12-28 19:50:56 [info     ] init johnnydist                [johnnydep.lib] dist=pyparsing>=2.0.2 parent=packaging>=17
2018-12-28 19:50:57 [info     ] init johnnydist                [johnnydep.lib] dist=six parent=packaging>=17
2018-12-28 19:50:57 [info     ] init johnnydist                [johnnydep.lib] dist=six parent=structlog
Traceback (most recent call last):
  File "/usr/local/bin/johnnydep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/johnnydep/cli.py", line 61, in main
    print(dist.serialise(fields=args.fields, format=args.output_format, recurse=args.recurse))
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 208-210: ordinal not in range(128)
```

**Comment by wimglenn** [comment]
I get the same error just changing the last line of your Dockerfile to:

     RUN python3 -c "print('\N{PILE OF POO}')"

So I don't think this is really johnnydep issue, some problem in Ubuntu container instead.
