### ISSUE TITLE
Exception while checking dependency tree

### ISSUE THREAD

**Issue by moredatarequired** [wimglenn/johnnydep#35]
When inspecting the tree for `apache-airflow` johnnydep encountered an exception and crashed.

Python 3.7.1, johnnydep 0.9, on Ubuntu 18.04

To reproduce:
`johnnydep apache-airflow` results in
```
...
Successfully built pendulum
Cleaning up...
  Removing source in /tmp/pip-wheel-zeov8gng/pendulum
Removed build tracker '/tmp/pip-req-tracker-41rjxxsm'
 [johnnydep.pipper] links={'https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl#sha256=c7769ce668c7a333d84e17fe8b524b1c45e7ee9f7908ad0a73e1eda7e6a5aebf', 'https://files.pythonhosted.org/packages/85/a5/9fc15751f9725923b170ad37d6c61031fc9e941bafd5288ca6ee51233284/pendulum-1.4.4.tar.gz#sha256=601e52cb0425e94b1784b6613a9085e0066ae1fa1915d18771884b67e93cac5c', 'https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl#sha256=5e79117472686ac0c4aef5bad5172ea73a1c2d1646b808c35926bd26bdfb0c08'}
Traceback (most recent call last):
  File "/home/hugh/.local/bin/johnnydep", line 10, in <module>
    sys.exit(main())
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/johnnydep/cli.py", line 62, in main
    print(dist.serialise(fields=args.fields, format=args.output_format, recurse=args.recurse))
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/johnnydep/lib.py", line 298, in serialise
    return tabulate.tabulate(table, headers="keys")
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/tabulate.py", line 1262, in tabulate
    tabular_data, headers, showindex=showindex)
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/tabulate.py", line 876, in _normalize_tabular_data
    rows = list(tabular_data)
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/johnnydep/lib.py", line 334, in gen_table
    for pre, _fill, node in anytree.RenderTree(johnnydist):
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/anytree/render.py", line 272, in __next
    children = node.children
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/johnnydep/lib.py", line 177, in children
    JohnnyDist(req_string=dep, parent=self)
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/johnnydep/lib.py", line 82, in __init__
    extra_index_url=self.extra_index_url,
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/cachetools/func.py", line 80, in wrapper
    v = func(*args, **kwargs)
  File "/home/hugh/.local/pipx/venvs/johnnydep/lib/python3.7/site-packages/johnnydep/pipper.py", line 129, in get
    raise Exception("Expected exactly 1 link downloaded")
Exception: Expected exactly 1 link downloaded
```

Thank you very much for the package. If I have some time I'll look into it more.

**Comment by wimglenn** [comment]
Thanks for the report. Should be fixed in master, a couple of other things I want to address before making a 1.0 release but you can install directly from github if you need the fix immediately.

**Comment by moredatarequired** [comment]
Thanks! That was such a fast fix. I was trying to get the project set up on my machine so I could investigate / submit a PR, but you finished before I really got started :)

I did run into one small issue specific to my machine, which I created #37 to fix.
