### ISSUE TITLE
pip 20 breaks pipper function `get`

### ISSUE THREAD

**Issue by augustoamerico** [wimglenn/johnnydep#50]
With pip 20, the assumptions of the function [pipper.get](https://github.com/wimglenn/johnnydep/blob/74351726b597c6b42fe436bac756beca5caaf452/johnnydep/pipper.py#L114) are broke.

I would suggest to create a factory of pip versions (with 19.X.X and 20.X.X, so two factories) to set the parsing output logic there.

What are your thoughts on this matter?

**Comment by wimglenn** [comment]
Didn’t I already fix this? Please upgrade to latest johnnydep (1.3) and check again.

**Comment by augustoamerico** [comment]
You are right, I haven't check for updates. Sorry to bother you with this - and thanks for the pointer!

**Comment by vstirbu** [comment]
The problem still exists with version 1.3 and pip 20. I've created a docker environment where it can be reproduced: https://github.com/vstirbu/johnnydep-test.

If I run `make run`, which runs in container `johnnydep stdlib-list`, I get the following error:

```
2020-01-27 13:23:22 [info     ] init johnnydist                [johnnydep.lib] dist=stdlib-list parent=None
Traceback (most recent call last):
  File "/usr/local/bin/johnnydep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/johnnydep/cli.py", line 63, in main
    dist = JohnnyDist(args.req, index_url=args.index_url, env=args.env, extra_index_url=args.extra_index_url)
  File "/usr/local/lib/python3.7/site-packages/johnnydep/lib.py", line 68, in __init__
    extra_index_url=extra_index_url,
  File "/usr/local/lib/python3.7/site-packages/cachetools/func.py", line 74, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/johnnydep/lib.py", line 383, in _get_info
    tmpdir=".",
  File "/usr/local/lib/python3.7/site-packages/cachetools/func.py", line 74, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/johnnydep/pipper.py", line 163, in get
    target, _headers = _download_dist(url, scratch_file, index_url, extra_index_url)
  File "/usr/local/lib/python3.7/site-packages/johnnydep/pipper.py", line 80, in _download_dist
    target, _headers = urlretrieve(url, scratch_file, auth=auth)
  File "/usr/local/lib/python3.7/site-packages/johnnydep/compat.py", line 31, in urlretrieve
    res = opener.open(url, data=data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 510, in open
    req = Request(fullurl, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/local/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/local/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'stdlib-list-0.6.0.tar.gz'
```

**Comment by vstirbu** [comment]
Upon further investigation is looks like this [segment](https://github.com/wimglenn/johnnydep/blob/master/johnnydep/pipper.py#L127-L152) does not return valid links is special situations. For example in the case of `stdlib-list` the returned links are:

```
['stdlib-list-0.6.0.tar.gz',
'https://files.pythonhosted.org/packages/85/1b/48e7ab73af72f49226651a0bb389e5d7c1db8daf9c6fa93f792c371a1787/stdlib-list-0.6.0.tar.gz#sha256=133cc99104f5a4e1604dc88ebb393529bd4c2b99ae7e10d46c0b596f3c67c3f0']
```

I've made a [quick and dirty filter](https://github.com/vstirbu/johnnydep/tree/feature/fix-v20) that considers valid links only strings starting with `http` or ending in `whl`. It seems to do the job in my case but my experience with pip in this context is very limited, so not sure what can go wrong...

**Comment by wimglenn** [comment]
@vstirbu   Thanks for the reproducer. Will have a fix out shortly.
